name: pid_oict
description: A Flutter app for browsing PID stops, viewing departures, and tracking vehicle positions on a map using the Golemio API.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.0
  flutter_svg: ^2.3.0
  latlong2: ^0.9.1
  meta: ^1.18.0
  path_provider: ^2.1.5
  pid_seeds:
    path: packages/pid_seeds
  slang: ^4.16.0
  slang_flutter: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/transport/
