name: pid_oict
description: A Flutter app for browsing PID stops, viewing departures, and tracking vehicle positions on a map using the Golemio API.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  pid_seeds:
    path: packages/pid_seeds

  cupertino_icons: ^1.0.8
  dio: ^5.8.0
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  flutter_map: ^8.3.0
  json_annotation: ^4.11.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.6.0
  freezed: ^3.2.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.13.0

flutter:
  uses-material-design: true
